#!/usr/bin/env python3
"""gen_stubs.py - turn a failed link's "undefined symbol" list into no-op stubs.

The host test binary compiles all of src/main.c, which imports ~240 Mac
Toolbox routines (windows, QuickDraw, files, sound, menus).  The rules under
test never need them, so each unresolved symbol becomes a C function that
returns 0 (or a zeroed global for `qd`-style data, which toolbox_shim.c
already defines).  The stubs carry no prototypes on purpose: this file is
compiled without the Mac headers, and C links by name only.

Usage: gen_stubs.py LINK_ERRORS.txt > stubs_auto.c
"""
import re
import sys

# Symbols that are data, not code (the SOLO_BUILD path in main.c defines the
# g* window/state globals itself, so none are expected here).
DATA = set()

def main(path):
    text = open(path, errors="replace").read()
    # Apple ld:   "_Foo", referenced from:
    # GNU ld/lld: undefined reference to `Foo'  /  undefined symbol: Foo
    names = set(re.findall(r'"_([A-Za-z_][A-Za-z0-9_]*)", referenced from', text))
    names |= set(re.findall(r"undefined reference to `([A-Za-z_][A-Za-z0-9_]*)'", text))
    names |= set(re.findall(r"undefined symbol: _?([A-Za-z_][A-Za-z0-9_]*)", text))
    out = ["/* generated by gen_stubs.py - do not edit; no-op Toolbox stubs */"]
    for n in sorted(names):
        if n in DATA:
            out.append(f"long {n}[64];")
        else:
            out.append(f"long {n}() {{ return 0; }}")
    print("\n".join(out))
    print(f"/* {len(names)} stubs */")

if __name__ == "__main__":
    main(sys.argv[1])
